//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonPCapplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonPCEntities : DbContext
    {
        public MonPCEntities()
            : base("name=MonPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIE> CATEGORIEs { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<CLIENT_PRODUIT> CLIENT_PRODUIT { get; set; }
        public virtual DbSet<FOURNISSEUR> FOURNISSEURs { get; set; }
        public virtual DbSet<PRODUIT> PRODUITs { get; set; }
        public virtual DbSet<ADMINISTRATEUR> ADMINISTRATEURs { get; set; }
    }
}
